# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/device_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'protos/device_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bprotos/device_service.proto\x12\x06\x64\x65vice\"J\n\x0bLayerConfig\x12\x12\n\ninput_size\x18\x01 \x01(\x05\x12\x13\n\x0boutput_size\x18\x02 \x01(\x05\x12\x12\n\nactivation\x18\x03 \x01(\t\"L\n\x0bInitRequest\x12*\n\rlayer_configs\x18\x01 \x03(\x0b\x32\x13.device.LayerConfig\x12\x11\n\tdevice_id\x18\x02 \x01(\x05\"1\n\x0cInitResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\x05\"9\n\x0e\x46orwardRequest\x12\x12\n\ninput_data\x18\x01 \x01(\x0c\x12\x13\n\x0binput_shape\x18\x02 \x03(\x05\"<\n\x0f\x46orwardResponse\x12\x13\n\x0boutput_data\x18\x01 \x01(\x0c\x12\x14\n\x0coutput_shape\x18\x02 \x03(\x05\"8\n\x0f\x42\x61\x63kwardRequest\x12\x11\n\tgrad_data\x18\x01 \x01(\x0c\x12\x12\n\ngrad_shape\x18\x02 \x03(\x05\"@\n\x10\x42\x61\x63kwardResponse\x12\x18\n\x10grad_output_data\x18\x01 \x01(\x0c\x12\x12\n\ngrad_shape\x18\x02 \x03(\x05\"&\n\rUpdateRequest\x12\x15\n\rlearning_rate\x18\x01 \x01(\x02\" \n\x0eUpdateResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\r\n\x0bPingRequest\"\x1e\n\x0cPingResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"%\n\x10TeraflopsRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\x05\"D\n\x11TeraflopsResponse\x12\x16\n\x0e\x66orward_tflops\x18\x01 \x01(\x02\x12\x17\n\x0f\x62\x61\x63kward_tflops\x18\x02 \x01(\x02\x32\xf4\x02\n\rDeviceService\x12\x37\n\nInitialize\x12\x13.device.InitRequest\x1a\x14.device.InitResponse\x12:\n\x07\x46orward\x12\x16.device.ForwardRequest\x1a\x17.device.ForwardResponse\x12=\n\x08\x42\x61\x63kward\x12\x17.device.BackwardRequest\x1a\x18.device.BackwardResponse\x12\x37\n\x06Update\x12\x15.device.UpdateRequest\x1a\x16.device.UpdateResponse\x12\x31\n\x04Ping\x12\x13.device.PingRequest\x1a\x14.device.PingResponse\x12\x43\n\x0cGetTeraflops\x12\x18.device.TeraflopsRequest\x1a\x19.device.TeraflopsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.device_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LAYERCONFIG']._serialized_start=39
  _globals['_LAYERCONFIG']._serialized_end=113
  _globals['_INITREQUEST']._serialized_start=115
  _globals['_INITREQUEST']._serialized_end=191
  _globals['_INITRESPONSE']._serialized_start=193
  _globals['_INITRESPONSE']._serialized_end=242
  _globals['_FORWARDREQUEST']._serialized_start=244
  _globals['_FORWARDREQUEST']._serialized_end=301
  _globals['_FORWARDRESPONSE']._serialized_start=303
  _globals['_FORWARDRESPONSE']._serialized_end=363
  _globals['_BACKWARDREQUEST']._serialized_start=365
  _globals['_BACKWARDREQUEST']._serialized_end=421
  _globals['_BACKWARDRESPONSE']._serialized_start=423
  _globals['_BACKWARDRESPONSE']._serialized_end=487
  _globals['_UPDATEREQUEST']._serialized_start=489
  _globals['_UPDATEREQUEST']._serialized_end=527
  _globals['_UPDATERESPONSE']._serialized_start=529
  _globals['_UPDATERESPONSE']._serialized_end=561
  _globals['_PINGREQUEST']._serialized_start=563
  _globals['_PINGREQUEST']._serialized_end=576
  _globals['_PINGRESPONSE']._serialized_start=578
  _globals['_PINGRESPONSE']._serialized_end=608
  _globals['_TERAFLOPSREQUEST']._serialized_start=610
  _globals['_TERAFLOPSREQUEST']._serialized_end=647
  _globals['_TERAFLOPSRESPONSE']._serialized_start=649
  _globals['_TERAFLOPSRESPONSE']._serialized_end=717
  _globals['_DEVICESERVICE']._serialized_start=720
  _globals['_DEVICESERVICE']._serialized_end=1092
# @@protoc_insertion_point(module_scope)
