import { AIModel } from "./columns";

export function getData(): AIModel[] {
  return [
    {
      id: "t-1",
      name: "GPT-2",
      type: "transformer",
      spots: "2/4",
      projectedEarnings: 0.3,
    },
    {
      id: "nn-1",
      name: "MNIST",
      type: "neuralnetwork",
      spots: "2/4",
      projectedEarnings: 0.05,
    },
    {
      id: "nn-3",
      name: "VGG-Compact",
      type: "neuralnetwork",
      spots: "2/2",
      projectedEarnings: 1.2,
    },
    {
      id: "t-3",
      name: "RoBERTa-Tiny",
      type: "transformer",
      spots: "3/4",
      projectedEarnings: 0.3,
    },
    {
      id: "nn-4",
      name: "DenseNet-S",
      type: "neuralnetwork",
      spots: "1/3",
      projectedEarnings: 4.1,
    },
    {
      id: "t-4",
      name: "XLM-Mini",
      type: "transformer",
      spots: "1/2",
      projectedEarnings: 2.5,
    },
    {
      id: "nn-5",
      name: "EfficientNet-Lite",
      type: "neuralnetwork",
      spots: "1/3",
      projectedEarnings: 4.8,
    },
    {
      id: "t-5",
      name: "ALBERT-Compact",
      type: "transformer",
      spots: "2/5",
      projectedEarnings: 1.7,
    },
    {
      id: "nn-6",
      name: "MobileNet-S",
      type: "neuralnetwork",
      spots: "2/2",
      projectedEarnings: 0.5,
    },
    {
      id: "t-6",
      name: "DistilBERT-S",
      type: "transformer",
      spots: "2/4",
      projectedEarnings: 1.4,
    },
    {
      id: "nn-7",
      name: "Inception-Mini",
      type: "neuralnetwork",
      spots: "1/2",
      projectedEarnings: 2.8,
    },
    {
      id: "t-7",
      name: "ELECTRA-Tiny",
      type: "transformer",
      spots: "1/4",
      projectedEarnings: 0.9,
    },
    {
      id: "nn-8",
      name: "SqueezeNet-S",
      type: "neuralnetwork",
      spots: "2/2",
      projectedEarnings: 0.2,
    },
    {
      id: "t-8",
      name: "Longformer-Mini",
      type: "transformer",
      spots: "3/3",
      projectedEarnings: 2.8,
    },
    {
      id: "nn-9",
      name: "ShuffleNet-S",
      type: "neuralnetwork",
      spots: "3/4",
      projectedEarnings: 1.6,
    },
    {
      id: "t-9",
      name: "DeBERTa-Lite",
      type: "transformer",
      spots: "1/3",
      projectedEarnings: 4.9,
    },
    {
      id: "nn-10",
      name: "Xception-Mini",
      type: "neuralnetwork",
      spots: "1/2",
      projectedEarnings: 0.1,
    },
  ];
}
